server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://doantotnghiep.cwo0n2hukiv0.us-east-1.rds.amazonaws.com:3306/Ecommerce
    username: admin
    password: admin123
  jpa:
    hibernate:
    #      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true