
###Signup
POST /api/signup HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "name": "hainh",
  "email": "nguyenhoanghai@gmail.com",
  "password": "abc@123"
}


###Login
POST /api/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "email":"nguyenhoanghai@gmail.com",
  "password" :"abc@123"
}


###Refresh Token
POST /api/handler-refresh-token HTTP/1.1
Host: 10.56.66.52:3000
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJlbWFpbCI6Im5ndXllbmhvYW5naGFpQGdtYWlsLmNvbSIsImlhdCI6MTcyOTU4ODYyMiwiZXhwIjoxNzI5NzYxNDIyfQ.Fut0gUmkGLjxIdbHxpSK5K_1cGwfUJddGRzOUvFC0XA
x-client-id: 22
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJlbWFpbCI6Im5ndXllbmhvYW5naGFpQGdtYWlsLmNvbSIsImlhdCI6MTcyOTU4ODYyMiwiZXhwIjoxNzMwMTkzNDIyfQ.08Hi-Yvn09T6KwJxiOOUQTtTC0ewRmuTb6MIX5sdboU"
}