
###Signup
POST /api/signup HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "name": "hainh",
  "email": "nguyenhoanghai@gmail.com",
  "password": "abc@123"
}


###Login
POST /api/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "email":"nguyenhoanghai@gmail.com",
  "password" :"abc@123"
}


###Refresh Token

POST /api/handler-refresh-token HTTP/1.1
Host: localhost:3000
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIxLCJlbWFpbCI6Im5ndXllbmhvYW5naGFpQGdtYWlsLmNvbSIsImlhdCI6MTcyOTYwODIzNCwiZXhwIjoxNzMwMjEzMDM0fQ.HBa8fmZgWgoypaH8hvKy0UOKjm1T_heA2D55nFawy-c
x-client-id: 21
Content-Type: application/json